# Generated by Django 5.0.9 on 2024-12-03 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_alter_collection_author_alter_collection_set_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collection",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="collection",
            name="set",
        ),
        migrations.AddField(
            model_name="collection",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="collection",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="collection",
            name="name",
            field=models.CharField(default="Untitled Collection", max_length=255),
        ),
        migrations.AddField(
            model_name="collection",
            name="sets",
            field=models.ManyToManyField(
                related_name="collections", to="myapp.flashcardset"
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
