# Generated by Django 5.0.9 on 2024-12-04 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_alter_collection_author"),
    ]

    operations = []
