# Generated by Django 5.0.9 on 2024-12-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0013_userdailycreation_last_reset"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
